#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.3 on Fri Apr 19 15:25:26 2019
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((534, 426))
        self.panel_master = wx.Panel(self, wx.ID_ANY)
        self.notebook = wx.Notebook(self.panel_master, wx.ID_ANY, style=wx.NB_FIXEDWIDTH | wx.NB_TOP)
        self.notebook_tab_settings = wx.Panel(self.notebook, wx.ID_ANY)
        self.text_ctrl_nickname = wx.TextCtrl(self.notebook_tab_settings, wx.ID_ANY, "")
        self.text_ctrl_username = wx.TextCtrl(self.notebook_tab_settings, wx.ID_ANY, "")
        self.text_ctrl_realname = wx.TextCtrl(self.notebook_tab_settings, wx.ID_ANY, "")
        self.text_ctrl_nickservpass = wx.TextCtrl(self.notebook_tab_settings, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.text_ctrl_serveraddress = wx.TextCtrl(self.notebook_tab_settings, wx.ID_ANY, "")
        self.text_ctrl_port = wx.TextCtrl(self.notebook_tab_settings, wx.ID_ANY, "")
        self.text_ctrl_serverpass = wx.TextCtrl(self.notebook_tab_settings, wx.ID_ANY, "")
        self.checkbox_autoreconnect = wx.CheckBox(self.notebook_tab_settings, wx.ID_ANY, "Auto Reconnect")
        self.checkbox_enablelogging = wx.CheckBox(self.notebook_tab_settings, wx.ID_ANY, "Enable Logging")
        self.text_ctrl_autojoinchans = wx.TextCtrl(self.notebook_tab_settings, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.button_startconnection = wx.Button(self.notebook_tab_settings, wx.ID_ANY, "Start Connection")
        self.text_ctrl_configfile = wx.TextCtrl(self.notebook_tab_settings, wx.ID_ANY, "")
        self.text_ctrl_logfile = wx.TextCtrl(self.notebook_tab_settings, wx.ID_ANY, "")
        self.button_loadconfig = wx.Button(self.notebook_tab_settings, wx.ID_ANY, "Load")
        self.button_saveconfig = wx.Button(self.notebook_tab_settings, wx.ID_ANY, "Save")
        self.button_clearconfig = wx.Button(self.notebook_tab_settings, wx.ID_ANY, "Clear")
        self.notebook_tab_console = wx.Panel(self.notebook, wx.ID_ANY)
        self.text_ctrl_consoleout = wx.TextCtrl(self.notebook_tab_console, wx.ID_ANY, "", style=wx.TE_MULTILINE | wx.TE_READONLY)
        self.text_ctrl_input = wx.TextCtrl(self.notebook_tab_console, wx.ID_ANY, "")
        self.button_sendmsg = wx.Button(self.notebook_tab_console, wx.ID_ANY, "Send")
        self.panel_statusbar = wx.Panel(self.panel_master, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Python IRC")
        self.text_ctrl_autojoinchans.SetMinSize((215, 152))
        self.button_sendmsg.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_18 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_16 = wx.BoxSizer(wx.VERTICAL)
        sizer_17 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_15 = wx.BoxSizer(wx.VERTICAL)
        sizer_11 = wx.BoxSizer(wx.VERTICAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_14 = wx.BoxSizer(wx.VERTICAL)
        sizer_13 = wx.BoxSizer(wx.VERTICAL)
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.StaticBoxSizer(wx.StaticBox(self.notebook_tab_settings, wx.ID_ANY, "Autojoin Channels"), wx.VERTICAL)
        sizer_6 = wx.StaticBoxSizer(wx.StaticBox(self.notebook_tab_settings, wx.ID_ANY, "Connection"), wx.VERTICAL)
        sizer_5 = wx.StaticBoxSizer(wx.StaticBox(self.notebook_tab_settings, wx.ID_ANY, "Identity"), wx.VERTICAL)
        label_nickname = wx.StaticText(self.notebook_tab_settings, wx.ID_ANY, "Nickname:")
        sizer_5.Add(label_nickname, 0, wx.ALIGN_CENTER_VERTICAL | wx.TOP, 4)
        sizer_5.Add(self.text_ctrl_nickname, 0, wx.EXPAND, 0)
        label_username = wx.StaticText(self.notebook_tab_settings, wx.ID_ANY, "Username:")
        sizer_5.Add(label_username, 0, wx.ALIGN_CENTER_VERTICAL | wx.TOP, 4)
        sizer_5.Add(self.text_ctrl_username, 0, wx.EXPAND, 0)
        label_realname = wx.StaticText(self.notebook_tab_settings, wx.ID_ANY, "Realname:")
        sizer_5.Add(label_realname, 0, wx.ALIGN_CENTER_VERTICAL | wx.TOP, 4)
        sizer_5.Add(self.text_ctrl_realname, 0, wx.EXPAND, 0)
        label_nickservpass = wx.StaticText(self.notebook_tab_settings, wx.ID_ANY, "NickServ Password:")
        sizer_5.Add(label_nickservpass, 0, wx.ALIGN_CENTER_VERTICAL | wx.TOP, 4)
        sizer_5.Add(self.text_ctrl_nickservpass, 0, wx.EXPAND, 0)
        sizer_4.Add(sizer_5, 1, wx.ALL | wx.EXPAND, 4)
        label_serveraddress = wx.StaticText(self.notebook_tab_settings, wx.ID_ANY, "Server Address:")
        sizer_6.Add(label_serveraddress, 0, wx.ALIGN_CENTER_VERTICAL | wx.TOP, 4)
        sizer_6.Add(self.text_ctrl_serveraddress, 0, wx.EXPAND, 0)
        label_port = wx.StaticText(self.notebook_tab_settings, wx.ID_ANY, "Port:")
        sizer_6.Add(label_port, 0, wx.ALIGN_CENTER_VERTICAL | wx.TOP, 4)
        sizer_6.Add(self.text_ctrl_port, 0, wx.EXPAND, 0)
        label_serverpass = wx.StaticText(self.notebook_tab_settings, wx.ID_ANY, "Server Password:")
        sizer_6.Add(label_serverpass, 0, wx.ALIGN_CENTER_VERTICAL | wx.TOP, 4)
        sizer_6.Add(self.text_ctrl_serverpass, 0, wx.EXPAND, 0)
        sizer_6.Add(self.checkbox_autoreconnect, 0, wx.ALIGN_CENTER_VERTICAL | wx.TOP, 10)
        sizer_6.Add(self.checkbox_enablelogging, 0, wx.ALIGN_CENTER_VERTICAL | wx.TOP, 6)
        sizer_4.Add(sizer_6, 1, wx.ALL | wx.EXPAND, 4)
        sizer_7.Add(self.text_ctrl_autojoinchans, 1, wx.EXPAND | wx.TOP, 4)
        label_autojoinchans = wx.StaticText(self.notebook_tab_settings, wx.ID_ANY, "Seperate channels with a comma or newline")
        label_autojoinchans.SetFont(wx.Font(8, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_7.Add(label_autojoinchans, 0, wx.TOP, 4)
        sizer_4.Add(sizer_7, 1, wx.ALL | wx.EXPAND, 4)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_10.Add(self.button_startconnection, 0, 0, 0)
        sizer_9.Add(sizer_10, 0, wx.EXPAND, 0)
        label_configfile = wx.StaticText(self.notebook_tab_settings, wx.ID_ANY, "Config File:", style=wx.ALIGN_RIGHT)
        sizer_13.Add(label_configfile, 0, wx.BOTTOM | wx.EXPAND | wx.TOP, 3)
        label_logfile = wx.StaticText(self.notebook_tab_settings, wx.ID_ANY, "Log File:", style=wx.ALIGN_RIGHT)
        sizer_13.Add(label_logfile, 0, wx.EXPAND | wx.TOP, 7)
        sizer_12.Add(sizer_13, 0, wx.LEFT | wx.RIGHT, 4)
        sizer_14.Add(self.text_ctrl_configfile, 0, wx.BOTTOM | wx.EXPAND, 4)
        sizer_14.Add(self.text_ctrl_logfile, 0, wx.EXPAND, 0)
        sizer_12.Add(sizer_14, 1, wx.LEFT | wx.RIGHT, 4)
        sizer_11.Add(sizer_12, 1, wx.EXPAND | wx.TOP, 1)
        sizer_9.Add(sizer_11, 1, wx.EXPAND | wx.LEFT | wx.RIGHT, 4)
        sizer_15.Add(self.button_loadconfig, 0, 0, 0)
        sizer_15.Add(self.button_saveconfig, 0, wx.BOTTOM | wx.TOP, 4)
        sizer_15.Add(self.button_clearconfig, 0, 0, 0)
        sizer_9.Add(sizer_15, 0, wx.EXPAND, 0)
        sizer_8.Add(sizer_9, 1, wx.ALL | wx.EXPAND, 4)
        sizer_3.Add(sizer_8, 1, wx.EXPAND, 0)
        self.notebook_tab_settings.SetSizer(sizer_3)
        sizer_16.Add(self.text_ctrl_consoleout, 1, wx.ALL | wx.EXPAND, 4)
        label_console_nickname = wx.StaticText(self.notebook_tab_console, wx.ID_ANY, "-")
        sizer_17.Add(label_console_nickname, 0, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 4)
        sizer_17.Add(self.text_ctrl_input, 1, wx.TOP, 1)
        sizer_17.Add(self.button_sendmsg, 0, wx.LEFT, 4)
        sizer_16.Add(sizer_17, 0, wx.ALL | wx.EXPAND, 4)
        self.notebook_tab_console.SetSizer(sizer_16)
        self.notebook.AddPage(self.notebook_tab_settings, "Settings")
        self.notebook.AddPage(self.notebook_tab_console, "Console")
        sizer_2.Add(self.notebook, 1, wx.ALL | wx.EXPAND, 0)
        label_statbarmsg = wx.StaticText(self.panel_statusbar, wx.ID_ANY, "-", style=wx.ALIGN_LEFT)
        sizer_18.Add(label_statbarmsg, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)
        label_statbarisonline = wx.StaticText(self.panel_statusbar, wx.ID_ANY, "Offline", style=wx.ALIGN_RIGHT)
        sizer_18.Add(label_statbarisonline, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)
        bitmap_statbarindicator = wx.StaticBitmap(self.panel_statusbar, wx.ID_ANY, wx.Bitmap("C:\\Users\\Chad\\PycharmProjects\\IrcBot2\\offline_circle.png", wx.BITMAP_TYPE_ANY))
        sizer_18.Add(bitmap_statbarindicator, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)
        self.panel_statusbar.SetSizer(sizer_18)
        sizer_2.Add(self.panel_statusbar, 0, wx.EXPAND, 0)
        self.panel_master.SetSizer(sizer_2)
        sizer_1.Add(self.panel_master, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class MyFrame


class MyApp(wx.App):
    def OnInit(self):
        self.frame_master = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame_master)
        self.frame_master.Show()
        return True

# end of class MyApp


if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
